# Generated by Django 4.1.4 on 2022-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("logo", models.ImageField(upload_to="images/")),
                ("sort", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("tag", models.TextField()),
                ("manager", models.CharField(max_length=50)),
                ("manager_call", models.CharField(max_length=50)),
            ],
        ),
    ]
