# Generated by Django 4.1.4 on 2022-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="club",
            name="manager",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="manager_call",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="tag",
            field=models.TextField(blank=True, null=True),
        ),
    ]
